name: api_gen
description:
  A simple Dart code generator that creates model classes (with fromJson/toJson)
  from a JSON schema, saving time on boilerplate in Flutter/Dart projects.
version: 0.0.4+1

repository: https://github.com/mrrda1969/api_gen
issue_tracker: https://github.com/mrrda1969/api_gen/issues
homepage: https://github.com/mrrda1969/api_gen
documentation: https://github.com/mrrda1969/api_gen#readme

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  api_gen: api_gen
